# bloco de codigo que pode gerar exceções

numero = int(input("Digite um número: "))
resultado = 10 / numero

try:
    print('ola')
except: (ValueError, TypeError)
print('')
    #trata exceções 
    
    
